version: '3.7'

services:
  movie_service:
    build: ./movie-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie-service/:/app/
    ports:
      - 8001:8000
    environment:
      - ASYNC_DATABASE_URL=postgresql+asyncpg://postgres:12345678@movie_db:5432/movie_db
      - SYNC_DATABASE_URL=postgresql://postgres:12345678@movie_db:5432/movie_db
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/

  cast_service:
    build: ./cast-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast-service/:/app/
    ports:
      - 8002:8000
    environment:
      - ASYNC_DATABASE_URL=postgresql+asyncpg://postgres:12345678@movie_db:5432/movie_db
      - SYNC_DATABASE_URL=postgresql://postgres:12345678@movie_db:5432/movie_db

  notificator_service:
    build: ./notificator-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./notificator-service/:/app/
    ports:
      - 8003:8000
    environment:
      - BOT_TOKEN=6548958040:AAGCwieQpClHf_mvCY94EhPOqfjzl4z4u-w
      - REDIS_HOST=localhost
      - REDIS_PORT=5432

  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=movie_db

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service
      - notificator_service

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=12345678
      - REDIS_PORT=6380
      - REDIS_DATABASES=1

volumes:
  postgres_data_movie:
